<?php 

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_guests',
	'title' => 'All Guests',
	'fields' => array(
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_638974df43f05',
			'label' => 'Basics & Categories',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_656a62f41a8ae',
			'label' => '(Column 3/12)',
			'name' => '',
			'aria-label' => '',
			'type' => 'acfe_column',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'columns' => '3/12',
			'endpoint' => 0,
			'acfe_permissions' => '',
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => 1,
			'allow_quickedit' => 1,
			'show_column' => 1,
			'show_column_weight' => 0,
			'show_column_sortable' => false,
			'key' => 'field_654b2c3f71272',
			'label' => 'Profile Image',
			'name' => 'profile_img',
			'aria-label' => '',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '100',
				'class' => '',
				'id' => '',
			),
			'uploader' => '',
			'return_format' => 'array',
			'acfe_thumbnail' => 1,
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'preview_size' => 'medium',
			'library' => 'all',
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_656a63031a8af',
			'label' => '(Column 9/12)',
			'name' => '',
			'aria-label' => '',
			'type' => 'acfe_column',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'columns' => '9/12',
			'endpoint' => 0,
			'acfe_permissions' => '',
		),
		array(
			'allow_backendsearch' => 0,
			'show_column_filter' => false,
			'allow_bulkedit' => 1,
			'allow_quickedit' => 1,
			'show_column' => 1,
			'show_column_weight' => 200,
			'show_column_sortable' => 1,
			'key' => 'field_6585cfef7e737',
			'label' => 'Guest Ranking',
			'name' => 'rank',
			'aria-label' => '',
			'type' => 'number',
			'instructions' => 'Celeb: 100 |	Voice: 200 | Content: 300 |	Comics: 400 | Artists: 500 |	Authors: 600 | Panelists & Vendors: 700 | Unframed: 900',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '30',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'min' => '',
			'max' => '',
			'placeholder' => '',
			'step' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => 0,
			'allow_bulkedit' => 1,
			'allow_quickedit' => 1,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_6585d0057e738',
			'label' => 'Days Attending',
			'name' => 'days',
			'aria-label' => '',
			'type' => 'taxonomy',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '30',
				'class' => '',
				'id' => '',
			),
			'taxonomy' => 'days',
			'add_term' => 1,
			'save_terms' => 1,
			'load_terms' => 1,
			'return_format' => 'id',
			'field_type' => 'multi_select',
			'allow_null' => 0,
			'acfe_bidirectional' => array(
				'acfe_bidirectional_enabled' => '0',
			),
			'acfe_settings' => '',
			'acfe_validate' => '',
			'acfe_permissions' => '',
			'bidirectional' => 0,
			'multiple' => 0,
			'bidirectional_target' => array(
			),
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => 0,
			'allow_bulkedit' => 1,
			'allow_quickedit' => 1,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_65e2fb3c6d89c',
			'label' => 'Guest Type (Main Cat)',
			'name' => 'xcat',
			'aria-label' => '',
			'type' => 'taxonomy',
			'instructions' => 'Placement in Main Guest Lists & defines Page Titles.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '30',
				'class' => '',
				'id' => '',
			),
			'taxonomy' => 'category',
			'add_term' => 1,
			'save_terms' => 1,
			'load_terms' => 1,
			'return_format' => 'id',
			'field_type' => 'select',
			'allow_null' => 1,
			'acfe_bidirectional' => array(
				'acfe_bidirectional_enabled' => '0',
			),
			'acfe_settings' => '',
			'acfe_validate' => '',
			'acfe_permissions' => '',
			'bidirectional' => 0,
			'multiple' => 0,
			'bidirectional_target' => array(
			),
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => 1,
			'allow_bulkedit' => 1,
			'allow_quickedit' => 1,
			'show_column' => 1,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_6326df33eb603',
			'label' => 'Guestlist',
			'name' => 'guestlist',
			'aria-label' => '',
			'type' => 'taxonomy',
			'instructions' => 'Select ALL events the guest has attended to show guest in Alumni Lists.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '30',
				'class' => '',
				'id' => '',
			),
			'taxonomy' => 'guestlist',
			'add_term' => 1,
			'save_terms' => 1,
			'load_terms' => 1,
			'return_format' => 'id',
			'field_type' => 'multi_select',
			'allow_null' => 1,
			'acfe_bidirectional' => array(
				'acfe_bidirectional_enabled' => '0',
			),
			'acfe_settings' => '',
			'acfe_validate' => '',
			'acfe_permissions' => '',
			'bidirectional' => 0,
			'multiple' => 0,
			'bidirectional_target' => array(
			),
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => 1,
			'allow_bulkedit' => 1,
			'allow_quickedit' => 1,
			'show_column' => 1,
			'show_column_weight' => 400,
			'show_column_sortable' => false,
			'key' => 'field_60c139d79a7b1',
			'label' => 'Guest Activities & Xperiences',
			'name' => 'xp',
			'aria-label' => '',
			'type' => 'taxonomy',
			'instructions' => 'Adds Guest to Xperience Pages',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '30',
				'class' => '',
				'id' => '',
			),
			'taxonomy' => 'guests',
			'add_term' => 1,
			'save_terms' => 1,
			'load_terms' => 1,
			'return_format' => 'id',
			'field_type' => 'multi_select',
			'allow_null' => 1,
			'acfe_bidirectional' => array(
				'acfe_bidirectional_enabled' => '0',
			),
			'acfe_settings' => '',
			'acfe_validate' => '',
			'acfe_permissions' => '',
			'bidirectional' => 0,
			'multiple' => 0,
			'bidirectional_target' => array(
			),
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => 1,
			'allow_bulkedit' => 1,
			'allow_quickedit' => 1,
			'show_column' => 1,
			'show_column_weight' => 600,
			'show_column_sortable' => false,
			'key' => 'field_617b496a50c74',
			'label' => 'Fandoms',
			'name' => 'fandoms',
			'aria-label' => '',
			'type' => 'taxonomy',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '40',
				'class' => '',
				'id' => '',
			),
			'taxonomy' => 'fandom',
			'add_term' => 1,
			'save_terms' => 1,
			'load_terms' => 1,
			'return_format' => 'id',
			'field_type' => 'multi_select',
			'allow_null' => 1,
			'acfe_bidirectional' => array(
				'acfe_bidirectional_enabled' => '0',
			),
			'acfe_settings' => '',
			'acfe_validate' => '',
			'acfe_permissions' => '',
			'bidirectional' => 0,
			'multiple' => 0,
			'bidirectional_target' => array(
			),
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => 0,
			'allow_bulkedit' => 1,
			'allow_quickedit' => 1,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_655851eeeb59b',
			'label' => 'Guest Xperience Status (Tags)',
			'name' => 'q_tags',
			'aria-label' => '',
			'type' => 'taxonomy',
			'instructions' => '(ie: Photo Ops Coming Soon or Autographs on Pre-Sale)	Activates dedicated content & Add Guest to related lists on Xperience Pages',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '60',
				'class' => '',
				'id' => '',
			),
			'taxonomy' => 'post_tag',
			'add_term' => 1,
			'save_terms' => 1,
			'load_terms' => 1,
			'return_format' => 'id',
			'field_type' => 'multi_select',
			'allow_null' => 0,
			'acfe_bidirectional' => array(
				'acfe_bidirectional_enabled' => '0',
			),
			'acfe_settings' => '',
			'acfe_validate' => '',
			'acfe_permissions' => '',
			'bidirectional' => 0,
			'multiple' => 0,
			'bidirectional_target' => array(
			),
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_656a630a1a8b0',
			'label' => '(Column Endpoint)',
			'name' => '',
			'aria-label' => '',
			'type' => 'acfe_column',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'endpoint' => 1,
			'acfe_permissions' => '',
			'columns' => '6/12',
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_6326db4d03460',
			'label' => 'Ops & Autos',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'allow_backendsearch' => 0,
			'show_column_filter' => false,
			'allow_bulkedit' => 1,
			'allow_quickedit' => 1,
			'show_column' => 1,
			'show_column_weight' => 500,
			'show_column_sortable' => 1,
			'key' => 'field_602441f475cc4',
			'label' => 'Auto Price:',
			'name' => 'autographs',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '15',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'allow_backendsearch' => 0,
			'show_column_filter' => false,
			'allow_bulkedit' => 1,
			'allow_quickedit' => 1,
			'show_column' => 1,
			'show_column_weight' => 500,
			'show_column_sortable' => 1,
			'key' => 'field_5e1ce0a30c21f',
			'label' => 'Ops Price:',
			'name' => 'photo_ops',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '15',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'allow_backendsearch' => 1,
			'show_column_filter' => false,
			'allow_bulkedit' => 1,
			'allow_quickedit' => 1,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_63897d741f198',
			'label' => 'Photo Ops Link',
			'name' => 'ops_url',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Link used on Photo Op Page, Ops Price & Op Day Message.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '30',
				'class' => '',
				'id' => '',
			),
			'default_value' => '[acf field="ops_url_fri" post_id="options" ]',
			'maxlength' => '',
			'placeholder' => '[acf field="ops_url_fri" post_id="options" ]',
			'prepend' => '',
			'append' => '',
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => 1,
			'allow_quickedit' => 1,
			'show_column' => 1,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_63d84cd9fc404',
			'label' => 'Group Photo Ops involved in:',
			'name' => 'grp_ops',
			'aria-label' => '',
			'type' => 'post_object',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '40',
				'class' => '',
				'id' => '',
			),
			'post_type' => array(
				0 => 'ticket',
			),
			'post_status' => '',
			'taxonomy' => array(
				0 => 'category:group-photo-ops',
			),
			'return_format' => 'id',
			'multiple' => 1,
			'save_custom' => 1,
			'save_post_type' => 'ticket',
			'save_post_status' => 'draft',
			'acfe_bidirectional' => array(
				'acfe_bidirectional_enabled' => '0',
			),
			'acfe_settings' => '',
			'acfe_validate' => '',
			'allow_null' => 0,
			'acfe_permissions' => '',
			'bidirectional' => 0,
			'ui' => 1,
			'bidirectional_target' => array(
			),
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_65d7df7b14e88',
			'label' => 'Additional Info',
			'name' => '',
			'aria-label' => '',
			'type' => 'accordion',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'open' => 1,
			'multi_expand' => 1,
			'endpoint' => 0,
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_661450f5745d1',
			'label' => '(Column 4/12)',
			'name' => '',
			'aria-label' => '',
			'type' => 'acfe_column',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'columns' => '4/12',
			'endpoint' => 0,
			'acfe_permissions' => '',
		),
		array(
			'allow_backendsearch' => 0,
			'show_column_filter' => false,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 0,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_66830e4bbb8f2',
			'label' => 'Celebrity Row Extras',
			'name' => 'celeb_xtras',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => 'Adds info underneath \'Autograph info\' on guest page and adds to Guest info on Celebrity Row Page.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '100',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'acfe_textarea_code' => 0,
			'acfe_settings' => '',
			'acfe_validate' => '',
			'maxlength' => '',
			'acfe_permissions' => '',
			'rows' => 3,
			'placeholder' => '',
			'new_lines' => 'br',
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_66145105745d2',
			'label' => '(Column 8/12)',
			'name' => '',
			'aria-label' => '',
			'type' => 'acfe_column',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'columns' => '8/12',
			'endpoint' => 0,
			'acfe_permissions' => '',
		),
		array(
			'allow_backendsearch' => 1,
			'show_column_filter' => false,
			'allow_bulkedit' => 1,
			'allow_quickedit' => 1,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_65e0cda09393a',
			'label' => 'Autos Coming Soon/Sold Out Message',
			'name' => 'autos_soon',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'This message is live ONLY when \'Autos Coming Soon\'	or \'Autos Sold Out\' Quick Tag is activated. Change Message as needed.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'COMING SOON',
			'acfe_settings' => '',
			'acfe_validate' => '',
			'maxlength' => '',
			'acfe_permissions' => '',
			'placeholder' => 'COMING SOON',
			'prepend' => '',
			'append' => '',
		),
		array(
			'allow_backendsearch' => 1,
			'show_column_filter' => false,
			'allow_bulkedit' => 1,
			'allow_quickedit' => 1,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_655853f8b17d0',
			'label' => 'Ops Coming Soon Message',
			'name' => 'ops_soon',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'This message is live ONLY when \'Ops Coming Soon\' or \'Ops Sold Out\' Quick Tag is activated. Change message as needed.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'COMING SOON',
			'acfe_settings' => '',
			'acfe_validate' => '',
			'maxlength' => '',
			'acfe_permissions' => '',
			'placeholder' => 'COMING SOON',
			'prepend' => '',
			'append' => '',
		),
		array(
			'allow_backendsearch' => 1,
			'show_column_filter' => false,
			'allow_bulkedit' => 1,
			'allow_quickedit' => 1,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_656a16d8c8991',
			'label' => 'Swaps Message',
			'name' => 'swaps',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Active when Photo Ops Swaps Quick Tag is used. Connected to Growtix Account URL. Only Update if Needed.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Swap a Photo Op NOW',
			'acfe_settings' => '',
			'acfe_validate' => '',
			'maxlength' => '',
			'acfe_permissions' => '',
			'placeholder' => 'Swap a Photo Op NOW',
			'prepend' => '',
			'append' => '',
		),
		array(
			'allow_backendsearch' => 1,
			'show_column_filter' => false,
			'allow_bulkedit' => 1,
			'allow_quickedit' => 1,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_65c8161e5d62d',
			'label' => 'Ops Days Override Message',
			'name' => 'ops_days',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Use when Photo Ops Days differ from actual days attending. Leave empty unless needed to override Photo Ops text links.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'acfe_settings' => '',
			'acfe_validate' => '',
			'maxlength' => '',
			'acfe_permissions' => '',
			'placeholder' => 'Friday & Saturday ONLY',
			'prepend' => '',
			'append' => '',
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_6614510c745d3',
			'label' => '(Column Endpoint)',
			'name' => '',
			'aria-label' => '',
			'type' => 'acfe_column',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'endpoint' => 1,
			'acfe_permissions' => '',
			'columns' => '6/12',
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_65d7df9514e89',
			'label' => 'Additional Info - END',
			'name' => '',
			'aria-label' => '',
			'type' => 'accordion',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'open' => 1,
			'multi_expand' => 1,
			'endpoint' => 1,
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_654af7a82d773',
			'label' => 'Header & Footer',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'acfe_permissions' => '',
			'selected' => 0,
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => 1,
			'allow_quickedit' => 1,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_65efb4c086dec',
			'label' => 'SubMenu',
			'name' => 'submenu',
			'aria-label' => '',
			'type' => 'post_object',
			'instructions' => 'Appears above Page Title',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'post_type' => array(
				0 => 'et_pb_layout',
			),
			'post_status' => array(
				0 => 'publish',
			),
			'taxonomy' => array(
				0 => 'layout_category:menus',
			),
			'return_format' => 'id',
			'multiple' => 0,
			'save_custom' => 0,
			'save_post_status' => 'publish',
			'acfe_bidirectional' => array(
				'acfe_bidirectional_enabled' => '0',
			),
			'acfe_settings' => '',
			'acfe_validate' => '',
			'allow_null' => 1,
			'acfe_permissions' => '',
			'bidirectional' => 0,
			'ui' => 1,
			'bidirectional_target' => array(
			),
			'save_post_type' => '',
		),
		array(
			'allow_backendsearch' => 0,
			'show_column_filter' => false,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 0,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_654af7a82d7b8',
			'label' => 'Subtitle',
			'name' => 'subtitle',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => 'Displays Subtitle below Profile Name',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '40',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'acfe_textarea_code' => 0,
			'acfe_settings' => '',
			'acfe_validate' => '',
			'maxlength' => '',
			'acfe_permissions' => '',
			'rows' => 2,
			'placeholder' => '',
			'new_lines' => '',
		),
		array(
			'allow_backendsearch' => 1,
			'show_column_filter' => false,
			'allow_bulkedit' => 1,
			'allow_quickedit' => 1,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_666245ae33b26',
			'label' => 'Subtext',
			'name' => 'subtext',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => 'Block of text appears under Subtitle',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '40',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'acfe_textarea_code' => 0,
			'acfe_settings' => '',
			'acfe_validate' => '',
			'maxlength' => '',
			'acfe_permissions' => '',
			'rows' => 2,
			'placeholder' => '',
			'new_lines' => '',
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_66305083f33bc',
			'label' => 'Footer',
			'name' => '',
			'aria-label' => '',
			'type' => 'accordion',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'open' => 0,
			'multi_expand' => 0,
			'endpoint' => 0,
			'acfe_permissions' => '',
		),
		array(
			'allow_backendsearch' => 1,
			'show_column_filter' => false,
			'allow_bulkedit' => 1,
			'allow_quickedit' => 1,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_667f62c4cedd7',
			'label' => 'Smallprint - Celeb Ops & Autos',
			'name' => 'sp_celeb',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => 'Celebrity Row & Photo Op Guest Xperience Categories activates this Smallprint - appears underneath profile. Change as needed.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '**Photo Op & Autograph experiences are subject to change.

**Autographs include one 8x10 photo. For more information about Autographs, Memorabilia Signings, Voice recordings, and other signing table opportunities visit the Celebrities Booth during the convention. Prices and options are subject to change.',
			'acfe_textarea_code' => 0,
			'acfe_settings' => '',
			'acfe_validate' => '',
			'maxlength' => '',
			'acfe_permissions' => '',
			'rows' => 4,
			'placeholder' => '',
			'new_lines' => 'br',
		),
		array(
			'allow_backendsearch' => 1,
			'show_column_filter' => false,
			'allow_bulkedit' => 1,
			'allow_quickedit' => 1,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_6685897eac952',
			'label' => 'Smallprint',
			'name' => 'sp_txt',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => 'Smallprint appears underneath profile. Change as needed.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '*Guest appearances are subject to change or cancellation.',
			'acfe_textarea_code' => 0,
			'acfe_settings' => '',
			'acfe_validate' => '',
			'maxlength' => '',
			'acfe_permissions' => '',
			'rows' => 4,
			'placeholder' => '',
			'new_lines' => '',
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_661455993b6c9',
			'label' => 'Footer END',
			'name' => '',
			'aria-label' => '',
			'type' => 'accordion',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'open' => 0,
			'multi_expand' => 0,
			'endpoint' => 1,
			'acfe_permissions' => '',
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_654af7a82c4b3',
			'label' => 'Buttons',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'allow_backendsearch' => 0,
			'show_column_filter' => false,
			'allow_bulkedit' => 1,
			'allow_quickedit' => 1,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_654af7a82c57d',
			'label' => 'Button Text',
			'name' => 'btn_txt',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'acfe_settings' => '',
			'acfe_validate' => '',
			'maxlength' => '',
			'acfe_permissions' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'allow_backendsearch' => 0,
			'show_column_filter' => false,
			'allow_bulkedit' => 1,
			'allow_quickedit' => 1,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_654af7a82c5cd',
			'label' => 'Button Link',
			'name' => 'btn_url',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'acfe_settings' => '',
			'acfe_validate' => '',
			'maxlength' => '',
			'acfe_permissions' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'allow_backendsearch' => 0,
			'show_column_filter' => false,
			'allow_bulkedit' => 1,
			'allow_quickedit' => 1,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_654af7a82c611',
			'label' => 'Button Text- 2',
			'name' => 'btn_txt_2',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'allow_backendsearch' => 0,
			'show_column_filter' => false,
			'allow_bulkedit' => 1,
			'allow_quickedit' => 1,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_654af7a82c654',
			'label' => 'Button Link- 2',
			'name' => 'btn_url_2',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_654af7a82d587',
			'label' => 'Galleries & Featured Posts',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_65bd69a1f0a1f',
			'label' => 'Featured Post Galleries',
			'name' => '',
			'aria-label' => '',
			'type' => 'accordion',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'open' => 1,
			'multi_expand' => 0,
			'endpoint' => 0,
			'acfe_permissions' => '',
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_656aa52509834',
			'label' => '(Column 4/12)',
			'name' => '',
			'aria-label' => '',
			'type' => 'acfe_column',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'columns' => '4/12',
			'endpoint' => 0,
		),
		array(
			'allow_backendsearch' => 0,
			'show_column_filter' => false,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 0,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_65838510efd55',
			'label' => 'Multi-Post Gallery - Title',
			'name' => 'gal_t',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '100',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 0,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_6583876c3fb25',
			'label' => 'Multi-Post Gallery - Post IDs',
			'name' => 'f_grid',
			'aria-label' => '',
			'type' => 'post_object',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '100',
				'class' => '',
				'id' => '',
			),
			'post_type' => array(
				0 => 'feature',
				1 => 'partner',
			),
			'post_status' => '',
			'taxonomy' => '',
			'return_format' => 'id',
			'multiple' => 1,
			'save_custom' => 0,
			'save_post_status' => 'publish',
			'acfe_bidirectional' => array(
				'acfe_bidirectional_enabled' => '0',
			),
			'allow_null' => 0,
			'bidirectional' => 0,
			'ui' => 1,
			'bidirectional_target' => array(
			),
			'save_post_type' => '',
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_656aa54509835',
			'label' => '(Column 4/12)',
			'name' => '',
			'aria-label' => '',
			'type' => 'acfe_column',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'columns' => '4/12',
			'endpoint' => 0,
		),
		array(
			'allow_backendsearch' => 0,
			'show_column_filter' => false,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 0,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_654af7a82d65f',
			'label' => 'Featured Post Title',
			'name' => 'fp_t',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '100',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 0,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_65838577efd56',
			'label' => 'Featured Post - Post IDs',
			'name' => 'feat_post',
			'aria-label' => '',
			'type' => 'post_object',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '100',
				'class' => '',
				'id' => '',
			),
			'post_type' => array(
				0 => 'feature',
				1 => 'partner',
			),
			'post_status' => array(
				0 => 'publish',
			),
			'taxonomy' => '',
			'return_format' => 'id',
			'multiple' => 1,
			'save_custom' => 0,
			'save_post_status' => 'publish',
			'acfe_bidirectional' => array(
				'acfe_bidirectional_enabled' => '0',
			),
			'allow_null' => 0,
			'bidirectional' => 0,
			'ui' => 1,
			'bidirectional_target' => array(
			),
			'save_post_type' => '',
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_656aa55809837',
			'label' => '(Column Endpoint)',
			'name' => '',
			'aria-label' => '',
			'type' => 'acfe_column',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'endpoint' => 1,
			'columns' => '6/12',
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_65bd6a03f0a22',
			'label' => 'Featured Post Galleries - END',
			'name' => '',
			'aria-label' => '',
			'type' => 'accordion',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'open' => 1,
			'multi_expand' => 1,
			'endpoint' => 1,
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_65bd69b1f0a20',
			'label' => 'Image Galleries',
			'name' => '',
			'aria-label' => '',
			'type' => 'accordion',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'open' => 0,
			'multi_expand' => 0,
			'endpoint' => 0,
			'acfe_permissions' => '',
		),
		array(
			'allow_backendsearch' => 1,
			'show_column_filter' => false,
			'allow_bulkedit' => 1,
			'allow_quickedit' => 1,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_66a9b6d5176ab',
			'label' => 'Dynamic Gallery Title',
			'name' => 'dyn_t',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '30',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'acfe_settings' => '',
			'acfe_validate' => '',
			'maxlength' => '',
			'acfe_permissions' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_66a9b6e4176ac',
			'label' => 'Dynamic Gallery Imgs',
			'name' => 'dyn_gal',
			'aria-label' => '',
			'type' => 'gallery',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '80',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'library' => 'all',
			'acfe_settings' => '',
			'acfe_validate' => '',
			'min' => '',
			'max' => '',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'acfe_permissions' => '',
			'insert' => 'append',
			'preview_size' => 'thumbnail',
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_65bd6a1ef0a23',
			'label' => 'Image Galleries - END',
			'name' => '',
			'aria-label' => '',
			'type' => 'accordion',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'open' => 1,
			'multi_expand' => 1,
			'endpoint' => 1,
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_654af7a82d841',
			'label' => 'Schedule',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'acfe_permissions' => '',
			'selected' => 0,
		),
		array(
			'allow_backendsearch' => 1,
			'show_column_filter' => false,
			'allow_bulkedit' => 1,
			'allow_quickedit' => 1,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_668dff0895896',
			'label' => 'Guest Schedule',
			'name' => 'sched_url',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '30',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'acfe_settings' => '',
			'acfe_validate' => '',
			'maxlength' => '',
			'acfe_permissions' => '',
			'placeholder' => '[acf field="sched_url" post_id="options" ]',
			'prepend' => '',
			'append' => '',
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => 1,
			'allow_quickedit' => 1,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_65b19b2483a6d',
			'label' => 'Date & Time',
			'name' => 'when',
			'aria-label' => '',
			'type' => 'date_time_picker',
			'instructions' => 'Use Calendar to indicate Date & Time of Guests featured event',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'display_format' => 'F j, Y g:i a',
			'return_format' => 'F j, Y @ g:i a',
			'first_day' => 0,
			'acfe_settings' => '',
			'acfe_validate' => '',
			'acfe_permissions' => '',
		),
		array(
			'allow_backendsearch' => 1,
			'show_column_filter' => false,
			'allow_bulkedit' => 1,
			'allow_quickedit' => 1,
			'show_column' => 1,
			'show_column_weight' => 1000,
			'show_column_sortable' => 1,
			'key' => 'field_65b19ac183a6c',
			'label' => 'Room/Booth #',
			'name' => 'where',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => 0,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 0,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_65aef99333be6',
			'label' => 'Offsite Location',
			'name' => 'offsite',
			'aria-label' => '',
			'type' => 'taxonomy',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '30',
				'class' => '',
				'id' => '',
			),
			'taxonomy' => 'venue',
			'add_term' => 1,
			'save_terms' => 1,
			'load_terms' => 1,
			'return_format' => 'id',
			'field_type' => 'select',
			'allow_null' => 0,
			'acfe_bidirectional' => array(
				'acfe_bidirectional_enabled' => '0',
			),
			'bidirectional' => 0,
			'multiple' => 0,
			'bidirectional_target' => array(
			),
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_65bd7cca87316',
			'label' => 'Schedule - END',
			'name' => '',
			'aria-label' => '',
			'type' => 'accordion',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'open' => 0,
			'multi_expand' => 0,
			'endpoint' => 1,
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_610ae11b7ba98',
			'label' => 'Postponed',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_610ae12b7ba99',
			'label' => 'Postponed Guest Verbage (pstpnd)',
			'name' => 'pstpnd',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => 'Get Postponed Guest Verbage from the Marketing Dept. If because of time or circumstance, it is not available, you can use the default verbage below. (Make sure that it is the default verbage below and NOT verbage from a previous year with irrelevant information.)',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '[page_title] unfortunately, canceled their appearance at the upcoming [acf field="event_title" post_id="options" ] due to scheduling conflicts. We are so sad they needed to postpone, but we hope to have them again in the near future!

In regards to the Photo Op with [page_title] that you already purchased, you have two options:

1. Upgrade or Swap to another product.
You may upgrade or swap your photo op and/or group photo op with [page_title] to another guest appearing at the show. Service fees will apply. All transactions are final.

To upgrade your Voucher, open the Photo Op confirmation email that was sent to you from GrowTix, and view your order. Click the purple button that says “Upgrade” or the purple button that says “Swap”. A new window will appear with a drop-down list of eligible guests. Select the product you would like to Upgrade or Swap to and pay the difference if applicable.

Note: We highly recommend you bring a printed copy of the QR code for each Photo Op that you
purchased.

2. Issue yourself a self-service refund.
You may receive a full refund for the Photo Op and/or Group Photo Op with [page_title ]. First, log into your Growtix account and view your order. You will see a red button below the [page_title ] Photo Op product that says “Refund Product”. Click “Refund Product”.

For more information visit our <a href="/help">HelpDesk</a>',
			'acfe_textarea_code' => 0,
			'maxlength' => '',
			'rows' => '',
			'placeholder' => '',
			'new_lines' => 'br',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'guest',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'field',
	'hide_on_screen' => array(
		0 => 'block_editor',
		1 => 'discussion',
		2 => 'comments',
		3 => 'revisions',
		4 => 'slug',
		5 => 'author',
		6 => 'format',
		7 => 'page_attributes',
		8 => 'featured_image',
		9 => 'categories',
		10 => 'tags',
		11 => 'send-trackbacks',
	),
	'active' => true,
	'description' => 'Celebrities & Featured Comic Creators, Artists, Writers, etc',
	'show_in_rest' => 1,
	'acfe_display_title' => 'Guests',
	'acfe_autosync' => array(
		0 => 'php',
		1 => 'json',
	),
	'acfe_permissions' => array(
		0 => 'super_admin',
		1 => 'administrator',
		2 => 'editor',
		3 => 'author',
	),
	'acfe_meta' => '',
	'acfe_note' => '',
	'acfe_form' => 1,
	'qef_simple_location_rules' => 0,
	'modified' => 1723018053,
));

endif;