<?php 

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_sitewide',
	'title' => '#Sitewide Event Info',
	'fields' => array(
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_6524b04b8ebcd',
			'label' => 'Basics',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'acfe_permissions' => '',
			'selected' => 0,
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_6553fb7f0ad4d',
			'label' => '(Column 3/12)',
			'name' => '',
			'aria-label' => '',
			'type' => 'acfe_column',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'columns' => '3/12',
			'endpoint' => 0,
			'acfe_permissions' => '',
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 0,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_64caae9ffd090',
			'label' => 'Event Logo',
			'name' => 'event_logo',
			'aria-label' => '',
			'type' => 'image',
			'instructions' => 'event_logo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '100',
				'class' => '',
				'id' => '',
			),
			'uploader' => '',
			'return_format' => 'id',
			'acfe_thumbnail' => 0,
			'acfe_settings' => '',
			'acfe_validate' => '',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'acfe_permissions' => '',
			'preview_size' => 'medium',
			'library' => 'all',
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_6553fd229748a',
			'label' => 'Shortcode Info',
			'name' => '',
			'aria-label' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '[acf field="" post_id="options" ]',
			'new_lines' => 'wpautop',
			'esc_html' => 0,
			'acfe_settings' => '',
			'acfe_permissions' => '',
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_6553fba00ad4f',
			'label' => '(Column 5/12)',
			'name' => '',
			'aria-label' => '',
			'type' => 'acfe_column',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'columns' => '5/12',
			'endpoint' => 0,
			'acfe_permissions' => '',
		),
		array(
			'allow_backendsearch' => 0,
			'show_column_filter' => false,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 0,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_6553faafcd728',
			'label' => 'Event Summery',
			'name' => 'event_summ',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => 'event_summ',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '100',
				'class' => '',
				'id' => '',
			),
			'default_value' => '[acf field="hashtag" post_id="options"] is happening on [acf field="date" post_id="options"] at the [acf field="venue" post_id="options"]- <a href="/event-info/#hours">More Info</a>',
			'acfe_textarea_code' => 0,
			'acfe_settings' => '',
			'acfe_validate' => '',
			'maxlength' => '',
			'acfe_permissions' => '',
			'rows' => 4,
			'placeholder' => '',
			'new_lines' => '',
		),
		array(
			'allow_backendsearch' => 0,
			'show_column_filter' => false,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 0,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_64caaf34fd091',
			'label' => 'Event Description',
			'name' => 'event_desc',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => 'event_desc',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '100',
				'class' => '',
				'id' => '',
			),
			'default_value' => '[acf field="event_title" post_id="options" ] is coming to the [acf field="venue" post_id="options"] from [acf field="date" post_id="options"] [acf field="tkt_txt" post_id="options" ] Meet your favorite Comic Book Creators, Artists, Authors, and Celebrities. Enjoy a variety of panels, exhibitors, features & activities. Cosplay as your favorite characters, meet up with other Cosplayers and Fans.',
			'acfe_textarea_code' => 0,
			'acfe_settings' => '',
			'acfe_validate' => '',
			'maxlength' => '',
			'acfe_permissions' => '',
			'rows' => 8,
			'placeholder' => '',
			'new_lines' => '',
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_6553fb900ad4e',
			'label' => '(Column 4/12)',
			'name' => '',
			'aria-label' => '',
			'type' => 'acfe_column',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'columns' => '4/12',
			'endpoint' => 0,
			'acfe_permissions' => '',
		),
		array(
			'allow_backendsearch' => 0,
			'show_column_filter' => false,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 0,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_655432ed93311',
			'label' => 'Event Title',
			'name' => 'event_title',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'event_title',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '100',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'acfe_settings' => '',
			'acfe_validate' => '',
			'maxlength' => '',
			'acfe_permissions' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'allow_backendsearch' => 0,
			'show_column_filter' => false,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 0,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_63fd2a37f383c',
			'label' => 'Event Hashtag',
			'name' => 'hashtag',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'hashtag',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '100',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#FanX24',
			'acfe_settings' => '',
			'acfe_validate' => '',
			'maxlength' => '',
			'acfe_permissions' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'allow_backendsearch' => 0,
			'show_column_filter' => false,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 0,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_63fd2a37f3879',
			'label' => 'Event Date',
			'name' => 'date',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'date',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '100',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'acfe_settings' => '',
			'acfe_validate' => '',
			'maxlength' => '',
			'acfe_permissions' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_63fd2a37f38b6',
			'label' => 'Venue',
			'name' => 'venue',
			'aria-label' => '',
			'type' => 'acfe_taxonomy_terms',
			'instructions' => 'venue',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '100',
				'class' => '',
				'id' => '',
			),
			'taxonomy' => array(
				0 => 'venue',
			),
			'allow_terms' => '',
			'allow_level' => '',
			'field_type' => 'select',
			'default_value' => array(
			),
			'return_format' => 'name',
			'ui' => 0,
			'allow_null' => 0,
			'multiple' => 0,
			'save_terms' => 0,
			'load_terms' => 0,
			'acfe_settings' => '',
			'acfe_validate' => '',
			'acfe_permissions' => '',
			'choices' => array(
			),
			'ajax' => 0,
			'placeholder' => '',
			'search_placeholder' => '',
			'layout' => '',
			'toggle' => 0,
			'allow_custom' => 0,
			'other_choice' => 0,
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_6525a9337c00a',
			'label' => '(Column Endpoint)',
			'name' => '',
			'aria-label' => '',
			'type' => 'acfe_column',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '40',
				'class' => '',
				'id' => '',
			),
			'endpoint' => 1,
			'acfe_permissions' => '',
			'columns' => '6/12',
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_657b52d52a95f',
			'label' => 'Socials',
			'name' => '',
			'aria-label' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'new_lines' => 'wpautop',
			'esc_html' => 0,
			'acfe_settings' => '',
			'acfe_permissions' => '',
		),
		array(
			'allow_backendsearch' => 0,
			'show_column_filter' => false,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 0,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_656fed5af6dff',
			'label' => 'Facebook',
			'name' => 'fb_url',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'fb_url',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '30',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'acfe_settings' => '',
			'acfe_validate' => '',
			'maxlength' => '',
			'acfe_permissions' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'allow_backendsearch' => 0,
			'show_column_filter' => false,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 0,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_656fed9bf6e01',
			'label' => 'Twitter',
			'name' => 'twit_url',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'twit_url',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '30',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'acfe_settings' => '',
			'acfe_validate' => '',
			'maxlength' => '',
			'acfe_permissions' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'allow_backendsearch' => 0,
			'show_column_filter' => false,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 0,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_656fed90f6e00',
			'label' => 'Instagram',
			'name' => 'insta_url',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'insta_url',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '30',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'acfe_settings' => '',
			'acfe_validate' => '',
			'maxlength' => '',
			'acfe_permissions' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_6525ae407d091',
			'label' => 'App',
			'name' => '',
			'aria-label' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'new_lines' => 'wpautop',
			'esc_html' => 0,
			'acfe_settings' => '',
			'acfe_permissions' => '',
		),
		array(
			'allow_backendsearch' => 0,
			'show_column_filter' => false,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 0,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_65372db850c9c',
			'label' => 'App Message',
			'name' => 'app_txt',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'app_txt',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '30',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'acfe_settings' => '',
			'acfe_validate' => '',
			'maxlength' => '',
			'acfe_permissions' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'allow_backendsearch' => 0,
			'show_column_filter' => false,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 0,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_64ed4fe462ba0',
			'label' => 'Apple App Store',
			'name' => 'app_url',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'app_url',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '30',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'acfe_settings' => '',
			'acfe_validate' => '',
			'maxlength' => '',
			'acfe_permissions' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'allow_backendsearch' => 0,
			'show_column_filter' => false,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 0,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_64ed505762ba1',
			'label' => 'Google Play',
			'name' => 'play_url',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'play_url',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '30',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'acfe_settings' => '',
			'acfe_validate' => '',
			'maxlength' => '',
			'acfe_permissions' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_65f525cfcdacd',
			'label' => 'Guests & Features',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'acfe_permissions' => '',
			'selected' => 0,
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_6525adf25174e',
			'label' => 'Guest & Feature Statuses',
			'name' => '',
			'aria-label' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'new_lines' => 'wpautop',
			'esc_html' => 0,
			'acfe_settings' => '',
			'acfe_permissions' => '',
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_65cad62c4e08c',
			'label' => 'TV & Film',
			'name' => 'tv_stat',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'tv_stat',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'acfe_settings' => '',
			'acfe_validate' => '',
			'maxlength' => '',
			'acfe_permissions' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_65cad65c4e08d',
			'label' => 'Authors',
			'name' => 'auth_stat',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'auth_stat',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'acfe_settings' => '',
			'acfe_validate' => '',
			'maxlength' => '',
			'acfe_permissions' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_65cad67e4e08e',
			'label' => 'Artists',
			'name' => 'artist_stat',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'artist_stat',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'acfe_settings' => '',
			'acfe_validate' => '',
			'maxlength' => '',
			'acfe_permissions' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_65cad6994e08f',
			'label' => 'Comic Creators',
			'name' => 'comic_stat',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'comic_stat',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'acfe_settings' => '',
			'acfe_validate' => '',
			'maxlength' => '',
			'acfe_permissions' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_65cad6c44e090',
			'label' => 'Panelists',
			'name' => 'pan_stat',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'pan_stat',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'acfe_settings' => '',
			'acfe_validate' => '',
			'maxlength' => '',
			'acfe_permissions' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'allow_backendsearch' => 0,
			'show_column_filter' => false,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 0,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_65cad6e44e091',
			'label' => 'Vendors',
			'name' => 'vendor_stat',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'vendor_stat',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'acfe_settings' => '',
			'acfe_validate' => '',
			'maxlength' => '',
			'acfe_permissions' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'allow_backendsearch' => 0,
			'show_column_filter' => false,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 0,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_65dd454dad8b8',
			'label' => 'Cosplayers',
			'name' => 'coser_stat',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'vendor_stat',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'acfe_settings' => '',
			'acfe_validate' => '',
			'maxlength' => '',
			'acfe_permissions' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'allow_backendsearch' => 0,
			'show_column_filter' => false,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 0,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_65caf6ff44e0f',
			'label' => 'Features & Activities',
			'name' => 'feat_stat',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'vend_stat',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'acfe_settings' => '',
			'acfe_validate' => '',
			'maxlength' => '',
			'acfe_permissions' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'allow_backendsearch' => 0,
			'show_column_filter' => false,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 0,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_65caf753026c9',
			'label' => 'Special Events',
			'name' => 'spec_stat',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'spec_stat',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'acfe_settings' => '',
			'acfe_validate' => '',
			'maxlength' => '',
			'acfe_permissions' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_65cbb3ff6022f',
			'label' => 'Info Status & Maps',
			'name' => '',
			'aria-label' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'new_lines' => 'wpautop',
			'esc_html' => 0,
			'acfe_settings' => '',
			'acfe_permissions' => '',
		),
		array(
			'allow_backendsearch' => 0,
			'show_column_filter' => false,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 0,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_65cbb6c56eee4',
			'label' => 'Hotels Status',
			'name' => 'hot_stat',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'hot_stat',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '30',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'acfe_settings' => '',
			'acfe_validate' => '',
			'maxlength' => '',
			'acfe_permissions' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'allow_backendsearch' => 0,
			'show_column_filter' => false,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 0,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_65af5fe2be0aa',
			'label' => 'Vendor List Status',
			'name' => 'vend_stat',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'vend_stat',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'acfe_settings' => '',
			'acfe_validate' => '',
			'maxlength' => '',
			'acfe_permissions' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'allow_backendsearch' => 0,
			'show_column_filter' => false,
			'allow_bulkedit' => 1,
			'allow_quickedit' => 1,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_65af5fe7be0ab',
			'label' => 'Vendor List URL',
			'name' => 'vend_url',
			'aria-label' => '',
			'type' => 'url',
			'instructions' => 'vend_url',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '30',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'acfe_settings' => '',
			'acfe_validate' => '',
			'acfe_permissions' => '',
			'placeholder' => '',
		),
		array(
			'allow_backendsearch' => 0,
			'show_column_filter' => false,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 0,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_65cbb29e7c27d',
			'label' => 'Map Status',
			'name' => 'map_stat',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'map_stat',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '30',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'acfe_settings' => '',
			'acfe_validate' => '',
			'maxlength' => '',
			'acfe_permissions' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 0,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_65f52bb73c172',
			'label' => 'Panel Room Map',
			'name' => 'map_2',
			'aria-label' => '',
			'type' => 'image',
			'instructions' => 'map_2',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '35',
				'class' => '',
				'id' => '',
			),
			'uploader' => '',
			'return_format' => 'array',
			'library' => 'all',
			'acfe_thumbnail' => 0,
			'acfe_settings' => '',
			'acfe_validate' => '',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'acfe_permissions' => '',
			'preview_size' => 'medium',
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 0,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_65f52a143c170',
			'label' => 'Vendor Floor Map',
			'name' => 'map_1',
			'aria-label' => '',
			'type' => 'image',
			'instructions' => 'map_1',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '35',
				'class' => '',
				'id' => '',
			),
			'uploader' => '',
			'return_format' => 'array',
			'library' => 'all',
			'acfe_thumbnail' => 0,
			'acfe_settings' => '',
			'acfe_validate' => '',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'acfe_permissions' => '',
			'preview_size' => 'medium',
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 0,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_65f52a143c170',
			'label' => 'Vendor Floor Map',
			'name' => 'map_1',
			'aria-label' => '',
			'type' => 'image',
			'instructions' => 'map_1',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '35',
				'class' => '',
				'id' => '',
			),
			'uploader' => '',
			'return_format' => 'array',
			'library' => 'all',
			'acfe_thumbnail' => 0,
			'acfe_settings' => '',
			'acfe_validate' => '',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'acfe_permissions' => '',
			'preview_size' => 'medium',
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 0,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_65f52bb73c172',
			'label' => 'Panel Room Map',
			'name' => 'map_2',
			'aria-label' => '',
			'type' => 'image',
			'instructions' => 'map_2',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '35',
				'class' => '',
				'id' => '',
			),
			'uploader' => '',
			'return_format' => 'array',
			'library' => 'all',
			'acfe_thumbnail' => 0,
			'acfe_settings' => '',
			'acfe_validate' => '',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'acfe_permissions' => '',
			'preview_size' => 'medium',
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_66454f93cf12f',
			'label' => 'Schedule',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'acfe_permissions' => '',
			'selected' => 0,
		),
		array(
			'allow_backendsearch' => 0,
			'show_column_filter' => false,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 0,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_65cbb1c09c5e7',
			'label' => 'Event Hours Status',
			'name' => 'hours_stat',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'hours_stat',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'acfe_settings' => '',
			'acfe_validate' => '',
			'maxlength' => '',
			'acfe_permissions' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_65cad60d4e08b',
			'label' => 'Event Hours Breakdown',
			'name' => '',
			'aria-label' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'new_lines' => 'wpautop',
			'esc_html' => 0,
			'acfe_settings' => '',
			'acfe_permissions' => '',
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_65f52fb671f5b',
			'label' => '(Column Endpoint)',
			'name' => '',
			'aria-label' => '',
			'type' => 'acfe_column',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'endpoint' => 1,
			'acfe_permissions' => '',
			'columns' => '6/12',
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_6668cd52ed03e',
			'label' => '(Column 4/12)',
			'name' => '',
			'aria-label' => '',
			'type' => 'acfe_column',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'columns' => '4/12',
			'endpoint' => 0,
			'acfe_permissions' => '',
		),
		array(
			'allow_backendsearch' => 0,
			'show_column_filter' => false,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 0,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_63fd2a37f38f4',
			'label' => 'Hours - Vendor Floor',
			'name' => 'event_hours',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => 'event_hours',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '100',
				'class' => '',
				'id' => '',
			),
			'default_value' => '<strong>Vendor Floor Hours:</strong> [acf field="vf_Thurs" post_id="options" ] | [acf field="vf_Fri" post_id="options" ] | [acf field="vf_Sat" post_id="options" ] - <a href="/vendor-floor/#hours">Find out More</a>',
			'acfe_textarea_code' => 0,
			'acfe_settings' => '',
			'acfe_validate' => '',
			'maxlength' => '',
			'acfe_permissions' => '',
			'rows' => 4,
			'placeholder' => '',
			'new_lines' => '',
		),
		array(
			'allow_backendsearch' => 0,
			'show_column_filter' => false,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 0,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_655424872f31a',
			'label' => 'Friday',
			'name' => 'vf_Fri',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'vf_Fri',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '100',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'acfe_settings' => '',
			'acfe_validate' => '',
			'maxlength' => '',
			'acfe_permissions' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'allow_backendsearch' => 0,
			'show_column_filter' => false,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 0,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_655424932f31b',
			'label' => 'Saturday',
			'name' => 'vf_Sat',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'vf_Sat',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '100',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'acfe_settings' => '',
			'acfe_validate' => '',
			'maxlength' => '',
			'acfe_permissions' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'allow_backendsearch' => 0,
			'show_column_filter' => false,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 0,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_655424582f319',
			'label' => 'Sunday',
			'name' => 'vf_Sun',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'vf_Sun | Thursday for FanX',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '100',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'acfe_settings' => '',
			'acfe_validate' => '',
			'maxlength' => '',
			'acfe_permissions' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'allow_backendsearch' => 0,
			'show_column_filter' => false,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 0,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_653703be48185',
			'label' => 'Vendor Floor Subtext',
			'name' => 'vf_subtext',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => 'vf_subtext',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '100',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'acfe_textarea_code' => 0,
			'acfe_settings' => '',
			'acfe_validate' => '',
			'maxlength' => '',
			'acfe_permissions' => '',
			'rows' => 8,
			'placeholder' => '',
			'new_lines' => 'br',
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_6668cd7aed03f',
			'label' => '(Column 4/12)',
			'name' => '',
			'aria-label' => '',
			'type' => 'acfe_column',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'columns' => '4/12',
			'endpoint' => 0,
			'acfe_permissions' => '',
		),
		array(
			'allow_backendsearch' => 0,
			'show_column_filter' => false,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 0,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_63fd4628eb46f',
			'label' => 'Hours - Panel Programming',
			'name' => 'panel_hours',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => 'panel_hours',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '100',
				'class' => '',
				'id' => '',
			),
			'default_value' => '<strong>Panel Programming Hours:</strong> [acf field="prg_Thurs" post_id="options" ] | [acf field="prg_Fri" post_id="options" ] | [acf field="prg_Sat" post_id="options" ] -<a href="/panels/#hours">Find out More</a>',
			'acfe_textarea_code' => 0,
			'acfe_settings' => '',
			'acfe_validate' => '',
			'maxlength' => '',
			'acfe_permissions' => '',
			'rows' => 4,
			'placeholder' => '',
			'new_lines' => '',
		),
		array(
			'allow_backendsearch' => 0,
			'show_column_filter' => false,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 0,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_65542fb9a7409',
			'label' => 'Friday',
			'name' => 'prg_Fri',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'prg_Fri',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '100',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'acfe_settings' => '',
			'acfe_validate' => '',
			'maxlength' => '',
			'acfe_permissions' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'allow_backendsearch' => 0,
			'show_column_filter' => false,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 0,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_65542fcca740a',
			'label' => 'Saturday',
			'name' => 'prg_Sat',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'prg_Sat',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '100',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'acfe_settings' => '',
			'acfe_validate' => '',
			'maxlength' => '',
			'acfe_permissions' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'allow_backendsearch' => 0,
			'show_column_filter' => false,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 0,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_65542f96a7408',
			'label' => 'Sunday',
			'name' => 'prg_Sun',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'prg_Sun | Thursday for FanX',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '100',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'acfe_settings' => '',
			'acfe_validate' => '',
			'maxlength' => '',
			'acfe_permissions' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'allow_backendsearch' => 0,
			'show_column_filter' => false,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 0,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_6554307ef39d9',
			'label' => 'Programming Subtext',
			'name' => 'prg_subtext',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => 'prg_subtext',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '100',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'acfe_textarea_code' => 0,
			'acfe_settings' => '',
			'acfe_validate' => '',
			'maxlength' => '',
			'acfe_permissions' => '',
			'rows' => 8,
			'placeholder' => '',
			'new_lines' => '',
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_6668cd7fed040',
			'label' => '(Column 4/12)',
			'name' => '',
			'aria-label' => '',
			'type' => 'acfe_column',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'columns' => '4/12',
			'endpoint' => 0,
			'acfe_permissions' => '',
		),
		array(
			'allow_backendsearch' => 0,
			'show_column_filter' => false,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 0,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_653702969b6a4',
			'label' => 'Hours - Registration',
			'name' => 'reg_hours',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => 'reg_hours',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '100',
				'class' => '',
				'id' => '',
			),
			'default_value' => '<strong>Registration Hours:</strong> [acf field="reg_Thurs" post_id="options" ] | [acf field="reg_Fri" post_id="options" ] | [acf field="reg_Sat" post_id="options" ] -<a href="/registration/#hours">Find out More</a>',
			'acfe_textarea_code' => 0,
			'acfe_settings' => '',
			'acfe_validate' => '',
			'maxlength' => '',
			'acfe_permissions' => '',
			'rows' => 4,
			'placeholder' => '',
			'new_lines' => '',
		),
		array(
			'allow_backendsearch' => 0,
			'show_column_filter' => false,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 0,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_6668d3d3b0540',
			'label' => 'Pre-Registration',
			'name' => 'pre_reg',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'pre_reg',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '100',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'acfe_settings' => '',
			'acfe_validate' => '',
			'maxlength' => '',
			'acfe_permissions' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'allow_backendsearch' => 0,
			'show_column_filter' => false,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 0,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_65542ff6a740c',
			'label' => 'Friday',
			'name' => 'reg_Fri',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'reg_Fri',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '100',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'acfe_settings' => '',
			'acfe_validate' => '',
			'maxlength' => '',
			'acfe_permissions' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'allow_backendsearch' => 0,
			'show_column_filter' => false,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 0,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_65543007a740d',
			'label' => 'Saturday',
			'name' => 'reg_Sat',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'reg_Sat',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '100',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'acfe_settings' => '',
			'acfe_validate' => '',
			'maxlength' => '',
			'acfe_permissions' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'allow_backendsearch' => 0,
			'show_column_filter' => false,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 0,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_65542fe4a740b',
			'label' => 'Sunday',
			'name' => 'reg_Sun',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'reg_Sun | Thursday for FanX',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '100',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'acfe_settings' => '',
			'acfe_validate' => '',
			'maxlength' => '',
			'acfe_permissions' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'allow_backendsearch' => 0,
			'show_column_filter' => false,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 0,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_65543091f39da',
			'label' => 'Registration Subtext',
			'name' => 'reg_subtext',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => 'reg_subtext',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '100',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'acfe_textarea_code' => 0,
			'acfe_settings' => '',
			'acfe_validate' => '',
			'maxlength' => '',
			'acfe_permissions' => '',
			'rows' => 3,
			'placeholder' => '',
			'new_lines' => '',
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_6668cd86ed041',
			'label' => '(Column Endpoint)',
			'name' => '',
			'aria-label' => '',
			'type' => 'acfe_column',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'endpoint' => 1,
			'acfe_permissions' => '',
			'columns' => '6/12',
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_65c69f12ef893',
			'label' => 'Outgoing Links & Status',
			'name' => '',
			'aria-label' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'new_lines' => 'wpautop',
			'esc_html' => 0,
			'acfe_settings' => '',
			'acfe_permissions' => '',
		),
		array(
			'allow_backendsearch' => 0,
			'show_column_filter' => false,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 0,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_6583a22a96af4',
			'label' => 'Growtix Schedule Status',
			'name' => 'sched_stat',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'sched_stat',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'acfe_settings' => '',
			'acfe_validate' => '',
			'maxlength' => '',
			'acfe_permissions' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'allow_backendsearch' => 0,
			'show_column_filter' => false,
			'allow_bulkedit' => 1,
			'allow_quickedit' => 1,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_61424e05e15ef',
			'label' => 'Growtix Schedule URL',
			'name' => 'sched_url',
			'aria-label' => '',
			'type' => 'url',
			'instructions' => 'sched_url',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '30',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'acfe_settings' => '',
			'acfe_validate' => '',
			'acfe_permissions' => '',
			'placeholder' => '',
		),
		array(
			'allow_backendsearch' => 0,
			'show_column_filter' => false,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 0,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_65f0be58a5c7d',
			'label' => 'PDF Schedule Status',
			'name' => 'pdf_sched_stat',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'pdf_sched_stat',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'acfe_settings' => '',
			'acfe_validate' => '',
			'maxlength' => '',
			'acfe_permissions' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'allow_backendsearch' => 0,
			'show_column_filter' => false,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 0,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_65f0be58a5c7d',
			'label' => 'PDF Schedule Status',
			'name' => 'pdf_sched_stat',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'pdf_sched_stat',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'acfe_settings' => '',
			'acfe_validate' => '',
			'maxlength' => '',
			'acfe_permissions' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'allow_backendsearch' => 0,
			'show_column_filter' => false,
			'allow_bulkedit' => 1,
			'allow_quickedit' => 1,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_65f0be68a5c7e',
			'label' => 'PDF Schedule URL',
			'name' => 'pdf_sched_url',
			'aria-label' => '',
			'type' => 'url',
			'instructions' => 'pdf_sched_url',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '30',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'acfe_settings' => '',
			'acfe_validate' => '',
			'acfe_permissions' => '',
			'placeholder' => '',
		),
		array(
			'allow_backendsearch' => 0,
			'show_column_filter' => false,
			'allow_bulkedit' => 1,
			'allow_quickedit' => 1,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_65f0be68a5c7e',
			'label' => 'PDF Schedule URL',
			'name' => 'pdf_sched_url',
			'aria-label' => '',
			'type' => 'url',
			'instructions' => 'pdf_sched_url',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '30',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'acfe_settings' => '',
			'acfe_validate' => '',
			'acfe_permissions' => '',
			'placeholder' => '',
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_6524b0648ebce',
			'label' => 'Tickets & Photo Ops',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'acfe_permissions' => '',
			'selected' => 0,
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_65540a35c1ee9',
			'label' => 'Tickets',
			'name' => '',
			'aria-label' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'new_lines' => 'wpautop',
			'esc_html' => 0,
			'acfe_settings' => '',
			'acfe_permissions' => '',
		),
		array(
			'allow_backendsearch' => 0,
			'show_column_filter' => false,
			'allow_bulkedit' => 1,
			'allow_quickedit' => 1,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_63a0f05b0c61d',
			'label' => 'Tickets Status',
			'name' => 'tkt_txt',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'tkt_txt',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '15',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'acfe_settings' => '',
			'acfe_validate' => '',
			'maxlength' => '',
			'acfe_permissions' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'allow_backendsearch' => 0,
			'show_column_filter' => false,
			'allow_bulkedit' => 1,
			'allow_quickedit' => 1,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_66904163f6188',
			'label' => 'Growtix Storefront Link',
			'name' => 'growtix_url',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'tkt_day_url',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'acfe_settings' => '',
			'acfe_validate' => '',
			'maxlength' => '',
			'acfe_permissions' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'allow_backendsearch' => 0,
			'show_column_filter' => false,
			'allow_bulkedit' => 1,
			'allow_quickedit' => 1,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_63a0f0790c61e',
			'label' => 'Tickets Link - Weekend',
			'name' => 'tkt_url',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'tkt_url',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '30',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'acfe_settings' => '',
			'acfe_validate' => '',
			'maxlength' => '',
			'acfe_permissions' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'allow_backendsearch' => 0,
			'show_column_filter' => false,
			'allow_bulkedit' => 1,
			'allow_quickedit' => 1,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_66903da86b38b',
			'label' => 'Tickets Link - Day',
			'name' => 'tkt_day_url',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'tkt_day_url',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '30',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'acfe_settings' => '',
			'acfe_validate' => '',
			'maxlength' => '',
			'acfe_permissions' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'allow_backendsearch' => 0,
			'show_column_filter' => false,
			'allow_bulkedit' => 1,
			'allow_quickedit' => 1,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_65d068d851493',
			'label' => 'Special Event Ticket Status',
			'name' => 'sptkt_stat',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'sptkt_stat',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'acfe_settings' => '',
			'acfe_validate' => '',
			'maxlength' => '',
			'acfe_permissions' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'allow_backendsearch' => 0,
			'show_column_filter' => false,
			'allow_bulkedit' => 1,
			'allow_quickedit' => 1,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_65d068d651492',
			'label' => 'Special Event Link',
			'name' => 'sptkt_url',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'sptkt_url',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '30',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'acfe_settings' => '',
			'acfe_validate' => '',
			'maxlength' => '',
			'acfe_permissions' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'allow_backendsearch' => 0,
			'show_column_filter' => false,
			'allow_bulkedit' => 1,
			'allow_quickedit' => 1,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_65d06b8a6b766',
			'label' => 'After Party Ticket Status',
			'name' => 'prty_stat',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'prty_stat',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'acfe_settings' => '',
			'acfe_validate' => '',
			'maxlength' => '',
			'acfe_permissions' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'allow_backendsearch' => 0,
			'show_column_filter' => false,
			'allow_bulkedit' => 1,
			'allow_quickedit' => 1,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_65d06b906b767',
			'label' => 'After Party Link',
			'name' => 'prty_url',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'prty_url',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '30',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'acfe_settings' => '',
			'acfe_validate' => '',
			'maxlength' => '',
			'acfe_permissions' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'allow_backendsearch' => 0,
			'show_column_filter' => false,
			'allow_bulkedit' => 1,
			'allow_quickedit' => 1,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_660b3e342764d',
			'label' => 'Photo Ops Link - Friday',
			'name' => 'ops_url_fri',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'ops_url_fri',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'acfe_settings' => '',
			'acfe_validate' => '',
			'maxlength' => '',
			'acfe_permissions' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_65835b889a98e',
			'label' => 'Photo Ops - Induvidual & Groups',
			'name' => '',
			'aria-label' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'new_lines' => 'wpautop',
			'esc_html' => 0,
			'acfe_settings' => '',
			'acfe_permissions' => '',
		),
		array(
			'allow_backendsearch' => 0,
			'show_column_filter' => false,
			'allow_bulkedit' => 1,
			'allow_quickedit' => 1,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_6536f7bed938e',
			'label' => 'Photo Ops Status',
			'name' => 'ops_txt',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'ops_txt',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'acfe_settings' => '',
			'acfe_validate' => '',
			'maxlength' => '',
			'acfe_permissions' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'allow_backendsearch' => 0,
			'show_column_filter' => false,
			'allow_bulkedit' => 1,
			'allow_quickedit' => 1,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_660b3e342764d',
			'label' => 'Photo Ops Link - Friday',
			'name' => 'ops_url_fri',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'ops_url_fri',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'acfe_settings' => '',
			'acfe_validate' => '',
			'maxlength' => '',
			'acfe_permissions' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'allow_backendsearch' => 0,
			'show_column_filter' => false,
			'allow_bulkedit' => 1,
			'allow_quickedit' => 1,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_658358babe635',
			'label' => 'Photo Ops - Saturday',
			'name' => 'ops_url_sat',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'ops_url_sat',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'acfe_settings' => '',
			'acfe_validate' => '',
			'maxlength' => '',
			'acfe_permissions' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'allow_backendsearch' => 0,
			'show_column_filter' => false,
			'allow_bulkedit' => 1,
			'allow_quickedit' => 1,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_658358ebbe637',
			'label' => 'Photo Ops - Sunday',
			'name' => 'ops_url_sun',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'ops_url_sun | Thursday for FanX',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'acfe_settings' => '',
			'acfe_validate' => '',
			'maxlength' => '',
			'acfe_permissions' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'allow_backendsearch' => 0,
			'show_column_filter' => false,
			'allow_bulkedit' => 1,
			'allow_quickedit' => 1,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_65835bc4588e0',
			'label' => 'Group Ops Status',
			'name' => 'grp_ops_txt',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'grp_ops_txt',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'acfe_settings' => '',
			'acfe_validate' => '',
			'maxlength' => '',
			'acfe_permissions' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'allow_backendsearch' => 0,
			'show_column_filter' => false,
			'allow_bulkedit' => 1,
			'allow_quickedit' => 1,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_6537014bd9391',
			'label' => 'Group Photo Ops Link',
			'name' => 'grp_ops_url',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'grp_ops_url',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '30',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'acfe_settings' => '',
			'acfe_validate' => '',
			'maxlength' => '',
			'acfe_permissions' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_65d7ee931eba6',
			'label' => 'Autographs & Celeb Row Extras',
			'name' => '',
			'aria-label' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'new_lines' => 'wpautop',
			'esc_html' => 0,
			'acfe_settings' => '',
			'acfe_permissions' => '',
		),
		array(
			'allow_backendsearch' => 0,
			'show_column_filter' => false,
			'allow_bulkedit' => 1,
			'allow_quickedit' => 1,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_65370146d9390',
			'label' => 'Autograph Status',
			'name' => 'autos_txt',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'autos_txt',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'acfe_settings' => '',
			'acfe_validate' => '',
			'maxlength' => '',
			'acfe_permissions' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'allow_backendsearch' => 0,
			'show_column_filter' => false,
			'allow_bulkedit' => 1,
			'allow_quickedit' => 1,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_65835f5b279f8',
			'label' => 'Autograph Link',
			'name' => 'autos_url',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'autos_url',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '30',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'acfe_settings' => '',
			'acfe_validate' => '',
			'maxlength' => '',
			'acfe_permissions' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'allow_backendsearch' => 0,
			'show_column_filter' => false,
			'allow_bulkedit' => 1,
			'allow_quickedit' => 1,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_65d7eebd1eba7',
			'label' => 'Celeb Extras Status',
			'name' => 'xtra_stat',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'xtra_stat',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'acfe_settings' => '',
			'acfe_validate' => '',
			'maxlength' => '',
			'acfe_permissions' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'allow_backendsearch' => 0,
			'show_column_filter' => false,
			'allow_bulkedit' => 1,
			'allow_quickedit' => 1,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_65d7eec41eba8',
			'label' => 'Celeb Extra Link',
			'name' => 'xtra_url',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'xtra_url',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '30',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'acfe_settings' => '',
			'acfe_validate' => '',
			'maxlength' => '',
			'acfe_permissions' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_656fa51501887',
			'label' => 'Participate & HelpDesk',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'acfe_permissions' => '',
			'selected' => 0,
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_65ca9b13c5da3',
			'label' => '(Column 7/12)',
			'name' => '',
			'aria-label' => '',
			'type' => 'acfe_column',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'columns' => '7/12',
			'endpoint' => 0,
			'acfe_permissions' => '',
		),
		array(
			'allow_backendsearch' => 0,
			'show_column_filter' => false,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 0,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_65ca9b46c5da5',
			'label' => 'Vendor Application Status',
			'name' => 'vend_app_stat',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'vend_app_stat',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '40',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'acfe_settings' => '',
			'acfe_validate' => '',
			'maxlength' => '',
			'acfe_permissions' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'allow_backendsearch' => 0,
			'show_column_filter' => false,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 0,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_65ca9b83c5da6',
			'label' => 'Vendor Application Link',
			'name' => 'vend_app_url',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'vend_app_url',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '60',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'acfe_settings' => '',
			'acfe_validate' => '',
			'maxlength' => '',
			'acfe_permissions' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'allow_backendsearch' => 0,
			'show_column_filter' => false,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 0,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_65ca9ba3c5da7',
			'label' => 'Programming Application Status',
			'name' => 'prog_app_stat',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'prog_app_stat',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '40',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'acfe_settings' => '',
			'acfe_validate' => '',
			'maxlength' => '',
			'acfe_permissions' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'allow_backendsearch' => 0,
			'show_column_filter' => false,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 0,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_65ca9ba7c5da8',
			'label' => 'Programming Application Link',
			'name' => 'prog_app_url',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'prog_app_url',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '60',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'acfe_settings' => '',
			'acfe_validate' => '',
			'maxlength' => '',
			'acfe_permissions' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'allow_backendsearch' => 0,
			'show_column_filter' => false,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 0,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_65caa5c2c47de',
			'label' => 'Features (Programming Exhibitor) Application Status',
			'name' => 'progex_app_stat',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'progex_app_stat',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '40',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'acfe_settings' => '',
			'acfe_validate' => '',
			'maxlength' => '',
			'acfe_permissions' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'allow_backendsearch' => 0,
			'show_column_filter' => false,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 0,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_65caa5bbc47dc',
			'label' => 'Features (Programming Exhibitor) Application Link',
			'name' => 'progex_app_url',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'progex_app_url',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '60',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'acfe_settings' => '',
			'acfe_validate' => '',
			'maxlength' => '',
			'acfe_permissions' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'allow_backendsearch' => 0,
			'show_column_filter' => false,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 0,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_65caa778801c8',
			'label' => 'Cosplay Judge/ Host Application Link',
			'name' => 'cosjudg_app_url',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'cosjudg_app_url',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '60',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'acfe_settings' => '',
			'acfe_validate' => '',
			'maxlength' => '',
			'acfe_permissions' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'allow_backendsearch' => 0,
			'show_column_filter' => false,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 0,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_65ca9be3c5daa',
			'label' => 'Special Guest Application Status',
			'name' => 'spec_app_stat',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'spec_app_stat',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '40',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'acfe_settings' => '',
			'acfe_validate' => '',
			'maxlength' => '',
			'acfe_permissions' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'allow_backendsearch' => 0,
			'show_column_filter' => false,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 0,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_65ca9be0c5da9',
			'label' => 'Special Guest Application Link',
			'name' => 'spec_app_url',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'spec_app_url',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '60',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'acfe_settings' => '',
			'acfe_validate' => '',
			'maxlength' => '',
			'acfe_permissions' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'allow_backendsearch' => 0,
			'show_column_filter' => false,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 0,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_65ca9c2ac5dac',
			'label' => 'Convention Crew Application Status',
			'name' => 'crew_app_stat',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'crew_app_stat',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '40',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'acfe_settings' => '',
			'acfe_validate' => '',
			'maxlength' => '',
			'acfe_permissions' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'allow_backendsearch' => 0,
			'show_column_filter' => false,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 0,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_65caa780801ca',
			'label' => 'Cosplay Contest Application Status',
			'name' => 'coscon_app_stat',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'coscon_app_stat',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '40',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'acfe_settings' => '',
			'acfe_validate' => '',
			'maxlength' => '',
			'acfe_permissions' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'allow_backendsearch' => 0,
			'show_column_filter' => false,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 0,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_65ca9c28c5dab',
			'label' => 'Convention Crew Application Link',
			'name' => 'crew_app_url',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'crew_app_url',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '60',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'acfe_settings' => '',
			'acfe_validate' => '',
			'maxlength' => '',
			'acfe_permissions' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'allow_backendsearch' => 0,
			'show_column_filter' => false,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 0,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_65caa77e801c9',
			'label' => 'Cosplay Contest Application Link',
			'name' => 'coscon_app_url',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'coscon_app_url',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '60',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'acfe_settings' => '',
			'acfe_validate' => '',
			'maxlength' => '',
			'acfe_permissions' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'allow_backendsearch' => 0,
			'show_column_filter' => false,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 0,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_66274265e760f',
			'label' => 'Press Application Status',
			'name' => 'press_app_stat',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'press_app_stat',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '40',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'acfe_settings' => '',
			'acfe_validate' => '',
			'maxlength' => '',
			'acfe_permissions' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'allow_backendsearch' => 0,
			'show_column_filter' => false,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 0,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_65caa773801c7',
			'label' => 'Cosplay Judge/Host Application Status',
			'name' => 'cosjudg_app_stat',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'cosjudg_app_stat',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '40',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'acfe_settings' => '',
			'acfe_validate' => '',
			'maxlength' => '',
			'acfe_permissions' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'allow_backendsearch' => 0,
			'show_column_filter' => false,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 0,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_6627428be7610',
			'label' => 'Press Application Link',
			'name' => 'press_app_url',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'press_app_url',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '60',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'acfe_settings' => '',
			'acfe_validate' => '',
			'maxlength' => '',
			'acfe_permissions' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_65ca8f3911e96',
			'label' => '(Column 5/12)',
			'name' => '',
			'aria-label' => '',
			'type' => 'acfe_column',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'columns' => '5/12',
			'endpoint' => 0,
			'acfe_permissions' => '',
		),
		array(
			'allow_backendsearch' => 0,
			'show_column_filter' => false,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 0,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_65bd7f5a24148',
			'label' => 'Growtix User Account Link',
			'name' => 'user_url',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'user_url',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '100',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'https://register.growtix.com/my_profile',
			'acfe_settings' => '',
			'acfe_validate' => '',
			'maxlength' => '',
			'acfe_permissions' => '',
			'placeholder' => 'https://register.growtix.com/my_profile',
			'prepend' => '',
			'append' => '',
		),
		array(
			'allow_backendsearch' => 0,
			'show_column_filter' => false,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 0,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_661d74022ec21',
			'label' => 'Sponsorship Deck PDF URL',
			'name' => 'sponsor_deck',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'sponsor_deck',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '100',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'acfe_settings' => '',
			'acfe_validate' => '',
			'maxlength' => '',
			'acfe_permissions' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'allow_backendsearch' => 0,
			'show_column_filter' => false,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 0,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_657b523be038e',
			'label' => 'ZenDesk URL - Main Page',
			'name' => 'zdesk',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'zdesk',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '100',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'acfe_settings' => '',
			'acfe_validate' => '',
			'maxlength' => '',
			'acfe_permissions' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'allow_backendsearch' => 0,
			'show_column_filter' => false,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 0,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_661dafaf95885',
			'label' => 'ZenDesk URL - General Form',
			'name' => 'zdesk_form',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'zdesk_form',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '100',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'acfe_settings' => '',
			'acfe_validate' => '',
			'maxlength' => '',
			'acfe_permissions' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'allow_backendsearch' => 0,
			'show_column_filter' => false,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 0,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_66a8a4e000e90',
			'label' => 'ASL Request Form',
			'name' => 'asl_form',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'asl_form',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '100',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'acfe_settings' => '',
			'acfe_validate' => '',
			'maxlength' => '',
			'acfe_permissions' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'allow_backendsearch' => 0,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_657b55ecf3362',
			'label' => 'ZDesk Footer Info',
			'name' => 'zdesk_foot',
			'aria-label' => '',
			'type' => 'wysiwyg',
			'instructions' => 'zdesk_foot',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '100',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'acfe_settings' => '',
			'acfe_validate' => '',
			'acfe_permissions' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 0,
			'delay' => 1,
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_65caa21714057',
			'label' => '(Column Endpoint)',
			'name' => '',
			'aria-label' => '',
			'type' => 'acfe_column',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'endpoint' => 1,
			'acfe_permissions' => '',
			'columns' => '6/12',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'fanx-theme',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'field',
	'hide_on_screen' => '',
	'active' => true,
	'description' => 'Custom Fields for Page Builder Fields, allowing quick & consistant content changes across website.',
	'show_in_rest' => 1,
	'acfe_display_title' => 'Sitewide Event info & Header Content',
	'acfe_autosync' => array(
		0 => 'php',
		1 => 'json',
	),
	'acfe_permissions' => array(
		0 => 'super_admin',
		1 => 'administrator',
		2 => 'editor',
	),
	'acfe_meta' => '',
	'acfe_note' => '',
	'acfe_form' => 1,
	'qef_simple_location_rules' => 0,
	'modified' => 1722328340,
));

endif;